# Generated by Django 6.1.1 on 2026-09-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incidente', models.CharField(max_length=200, verbose_name='Nombre del incidente')),
                ('ticket', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ticket generado')),
                ('prioridad', models.CharField(choices=[('P1', 'P1 - Crítica'), ('P2', 'P2 - Alta'), ('P3', 'P3 - Media'), ('P4', 'P4 - Baja')], default='P3', max_length=2, verbose_name='Prioridad')),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_gestion', 'En gestión'), ('resuelto', 'Resuelto')], default='abierto', max_length=20, verbose_name='Estado')),
                ('afectacion_cliente', models.CharField(choices=[('Si', 'Sí'), ('No', 'No')], default='No', max_length=2, verbose_name='Afectación a cliente')),
                ('como_se_detecto', models.CharField(blank=True, max_length=200, null=True, verbose_name='¿Cómo se detectó?')),
                ('reporte_inicial', models.CharField(blank=True, max_length=200, null=True, verbose_name='Reporte inicial')),
                ('asignado_a', models.CharField(blank=True, max_length=200, null=True, verbose_name='Asignado a')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('solucion', models.TextField(blank=True, null=True, verbose_name='Solución')),
                ('hora_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Hora inicio de falla')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Incidente',
                'verbose_name_plural': 'Incidentes',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
