# Generated by Django 6.1.1 on 2026-09-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidente',
            name='como_se_detecto',
            field=models.CharField(blank=True, choices=[('Monitoreo', 'Monitoreo'), ('Usuario Final', 'Usuario Final'), ('Proveedor', 'Proveedor'), ('Otro', 'Otro')], max_length=20, null=True, verbose_name='¿Cómo se detectó?'),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='reporte_inicial',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Cómo se detectó el incidente'),
        ),
    ]
