# Generated by Django 6.1.1 on 2026-09-24 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0002_alter_incidente_como_se_detecto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Descripción del avance')),
                ('hora', models.DateTimeField(auto_now_add=True, verbose_name='Hora del avance')),
                ('incidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='incidentes.incidente')),
            ],
            options={
                'verbose_name': 'Avance',
                'verbose_name_plural': 'Avances',
                'ordering': ['hora'],
            },
        ),
    ]
