# Generated by Django 6.1.1 on 2026-09-24 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0003_avance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del área')),
                ('incidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='incidentes.incidente')),
            ],
            options={
                'verbose_name': 'Área involucrada',
                'verbose_name_plural': 'Áreas involucradas',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la persona')),
                ('incidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='incidentes.incidente')),
            ],
            options={
                'verbose_name': 'Persona involucrada',
                'verbose_name_plural': 'Personas involucradas',
            },
        ),
    ]
