# Generated by Django 6.1.1 on 2026-09-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0004_area_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidente',
            name='ticket',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Ticket generado'),
        ),
    ]
