# Generated by Django 6.1.1 on 2026-09-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0005_alter_incidente_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boquilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Mensaje de la boquilla')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Boquilla',
                'verbose_name_plural': 'Boquillas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
