# Generated by Django 6.1.1 on 2026-09-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0006_boquilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='boquilla',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Nombre de la boquilla'),
        ),
    ]
