"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# python-dotenv: lee el archivo .env y carga sus valores para poder usarlos aqui.
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Cargamos el archivo .env que esta en la raiz del proyecto.
# A partir de aqui podemos leer sus valores con os.environ.get('NOMBRE').
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Leemos la clave secreta desde el .env. Si no existe, usamos una por defecto.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-$cr#+lm#cawf2*itdyorsh7b0il@b_(6b!g7xv7kj6ovd4isa*'
)

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG viene del .env como texto ('True'/'False'); lo comparamos para volverlo booleano.
# En local no hay variable DEBUG -> queda True. En Render pondremos DEBUG=False.
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# ALLOWED_HOSTS: dominios/hosts autorizados a servir la app.
# En local incluimos 127.0.0.1 y localhost. En produccion agregamos el dominio
# del servidor mediante la variable de entorno ALLOWED_HOSTS (separada por comas).
ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

_hosts_extra = os.environ.get('ALLOWED_HOSTS', '')
if _hosts_extra:
    ALLOWED_HOSTS += [h.strip() for h in _hosts_extra.split(',') if h.strip()]

# Render expone el dominio del servicio en esta variable; lo agregamos solo.
_render_host = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if _render_host:
    ALLOWED_HOSTS.append(_render_host)

# CSRF_TRUSTED_ORIGINS: orígenes https confiables para formularios (obligatorio en
# producción con dominio propio). Se arma a partir de los hosts extra y el de Render.
CSRF_TRUSTED_ORIGINS = []
for _h in ([_render_host] if _render_host else []) + \
          ([h.strip() for h in _hosts_extra.split(',') if h.strip()]):
    CSRF_TRUSTED_ORIGINS.append('https://' + _h)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Nuestras apps (las que creamos nosotros)
    'incidentes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise sirve los archivos estaticos (CSS/JS) en produccion.
    # Debe ir justo despues de SecurityMiddleware.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'incidentes.context_processors.atajos_navegacion',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        # Motor PostgreSQL (Supabase usa PostgreSQL).
        'ENGINE': 'django.db.backends.postgresql',
        # Todos estos valores se leen del archivo .env (no van escritos aqui).
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST'),
        'PORT': os.environ.get('DB_PORT'),
        # Supabase exige conexión cifrada (SSL) desde servidores externos.
        'OPTIONS': {
            'sslmode': os.environ.get('DB_SSLMODE', 'require'),
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'es-hn'

TIME_ZONE = 'America/Tegucigalpa'

USE_I18N = True

USE_TZ = True

# USE_L10N/formatos: al desactivar el formateo automatico por idioma y definir
# nuestros propios formatos, mostramos la hora en 24h (militar), sin am/pm.
# %H = hora en 24h, %M = minutos, %d/%m/%Y = dia/mes/anio.
DATETIME_FORMAT = 'd/m/Y H:i'
TIME_FORMAT = 'H:i'
DATE_FORMAT = 'd/m/Y'

# Formato que aceptan los campos de fecha/hora al ESCRIBIR en formularios (24h).
DATETIME_INPUT_FORMATS = ['%Y-%m-%dT%H:%M', '%d/%m/%Y %H:%M']


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

# STATICFILES_DIRS: carpetas donde Django busca archivos estaticos (CSS, JS, imagenes)
# durante el desarrollo. Aqui apuntamos a una carpeta "static" en la raiz del proyecto.
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# STATIC_ROOT: carpeta donde 'collectstatic' junta todos los estaticos para
# servirlos en produccion. Render ejecuta collectstatic durante el build.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise: comprime y cachea los estaticos en produccion.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Clave primaria por defecto (evita un warning del check).
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
# Por ahora el proyecto no envía correos; usamos el backend de consola
# (los "correos" se imprimen en la terminal). Si más adelante se necesita
# enviar correos de verdad, se cambia a un backend SMTP.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# ------------------------------------------------------------------
# Seguridad en PRODUCCIÓN (solo se activa cuando DEBUG = False).
# En local (DEBUG = True) no aplica, para no forzar HTTPS al desarrollar.
# ------------------------------------------------------------------
if not DEBUG:
    # Redirige todo el tráfico HTTP a HTTPS.
    SECURE_SSL_REDIRECT = True
    # Cookies de sesión y CSRF solo por HTTPS.
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # HSTS: obliga a los navegadores a usar HTTPS (1 año).
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Render sirve detrás de un proxy; esto indica que la conexión original es HTTPS.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
